### ISSUE TITLE
Dwa oddzielne konta naraz 

### ISSUE THREAD

**Issue by lwojcik** [lwojcik/Mastodon-Poradnik.pl#14]
Gdzieś w treści jest wzmianka na temat trzymania dwóch otwartych kont w dwóch osobnych kartach przeglądarki. Ale co zrobić, gdy ma się dwa konta na na tym samym serwerze, np. prywatne i firmowe?

(do zbadania: osobne profile / kontenery w przeglądarkach, alternatywne fronty do Mastodona, inne narzędzia które być może istnieją)

**Comment by sjbat** [comment]
Ze znanych mi klientów webowych (głównie z takich korzystam) wiele kont (również na tej samej instancji) obsługują Mangan i Pinafore

Podczas procesu oauth, jeśli podpowiadane jest "zalogowane" w browserze konto, należy się wylogować, zalogować ponownie na nowym, i dopiero udzielić autoryzacji.
