### ISSUE TITLE
Mastodon nie ma funkcji X, którą miał Twitter / Usenet / cokolwiek

### ISSUE THREAD

**Issue by lwojcik** [lwojcik/Mastodon-Poradnik.pl#9]
Opowiedzieć krótko, czym jest Mastodon w kontekście całego fediwersum (i czym różni się rozwój takiego projektu od rozwoju komercyjnych serwisów) oraz kto (i ile osób) i jak faktycznie nim zarządza. Celem odpowiedzi nie jest zbywanie tego typu uwag, a raczej uczciwe wytłumaczenie, dlaczego nie możemy mieć wszystkiego od razu + dlaczego z perspektywy UI/UX nie zawsze jest tak fajnie i miło jak na innych społecznościówkach + jak z tym żyć.

**Comment by sjbat** [comment]
Napisałem o tym na swoim blogu: https://zb3.org/m0bi13/czym-mozecie-byc-zdziwieni-po-przejsciu-z-twittera-do-mastodon

Jeśli chcesz wykorzystać całość lub fragmenty to zapraszam.

**Comment by lwojcik** [comment]
Odpuszczam na razie to pytanie. Może kiedyś zrobię jeszcze jedno podejście do niego.

Krótka odpowiedź moim zdaniem zbyt mocno spłyca temat (nie chcę pisać "bo Eugen tak chciał" i linkować do repo Mastodona). A w długiej odpowiedzi zaczynam drążyć historię fediwersum i znów robi się nie na temat. Za mało tu jeszcze widziałem, żeby kompetentnie opowiadać o historii, w której sam nie uczestniczyłem.
